# Docker compose file with nuxt in /web, rust in /api
version: '3.7'
services:
  web:
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    command: npm run dev
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    command: cargo watch -x run
  db:
    image: mariadb
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Csec8m5VQH
      MYSQL_DATABASE: projet_db
      MYSQL_USER: projet
      MYSQL_PASSWORD: kCG6X6vzwU