# Docker compose file with nuxt in /web, rust in /api
version: '3.7'
services:
  web:
    build: ./web
    ports:
      - 3000:3000
    volumes:
      - ./web:/app
    command: npm run dev
    networks:
      - nuxt-network
  api:
    build: ./api
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    networks:
      - nuxt-network
    environment:
      - ROCKET_DATABASES={projet_db={url="mysql://projet:kCG6X6vzwU@db:3306/projet_db"}}
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    volumes:
      - ./mariadb:/var/lib/mysql
    environment:
      MYSQL_DATABASE: projet_db
      MYSQL_USER: projet
      MYSQL_PASSWORD: kCG6X6vzwU
      MYSQL_ROOT_PASSWORD: Csec8m5VQH
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: bridge